version: '3.8'

services:
  linkedin:
    build: .
    ports:
      - "5900:5900"
      - "6080:6080"
    volumes:
      - ./linkedin/downloads:/app/linkedin/downloads
    env_file:
      - .env
    environment:
      - HEADLESS=false
      - DOWNLOADS_DIR=/app/linkedin/downloads
      - APP_MODULE=linkedin.src.main
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    command: ["--storage", "/app/linkedin_storage.json"]
    depends_on:
      - db
    # O comando padrão do Dockerfile será executado, mas você pode sobrescrevê-lo aqui se precisar
    # command: ["python", "-m", "src.main", "--storage", "/app/storage_state.json"]

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Porta padrão do PostgreSQL

  instagram:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - APP_MODULE=instagram.main
      - META_GRAPH_BASE=${META_GRAPH_BASE}
      - PAGE_ID=${PAGE_ID}
      - IG_ACCOUNT_ID=${IG_ACCOUNT_ID}
      - META_CLIENT_ID=${META_CLIENT_ID}
      - META_CLIENT_SECRET=${META_CLIENT_SECRET}
      - PORT=8000
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
    command: []
    depends_on:
      - db

volumes:
  db_data: